### PR TITLE
adjust camelCase detection to also find leading capitals (fixes #15)

### LINKED ISSUE #15: attributes starting with capital letters are encoded incorrectly
`encoder.encode("Prop:from")` returns `"Prop:from"` instead of `:u:prop:from`.

### PR DESCRIPTION
**Pull request by christopherjbaker**
Interestingly, the camelCase detector missed leading capitals, but the camelCase replacer caught them all, so `FooBar` was fixed properly but `Foobar` was not.

### CODE REVIEW

File: can-attribute-encoder-test.js [hunk 1]
```diff
@@ -10,6 +10,8 @@ QUnit.test('encoding / decoding', function() {
 		'on:fooBar:by:bazQuz': 'on:foo:u:bar:by:baz:u:quz',
 		'vm:sProp:to': 'vm:s:u:prop:to',
 		'fooBar:to': 'foo:u:bar:to',
+		'FooBar:to': ':u:foo:u:bar:to',
+		'Foobar:to': ':u:foobar:to',
```
Comment (phillipskevin) [inline can-attribute-encoder-test.js]: Can you add these cases to the `encoded values should work with setAttribute` test also? I know the spec says attributes can start with `:`, but it would be good to have our tests confirm it.

Comment (christopherjbaker) [reply can-attribute-encoder-test.js]: done!
